### ISSUE TITLE
Does not work out of the box with latest CLDR 38.1

### ISSUE THREAD

**Issue by psttf** [cquiroz/sbt-locales#83]
Builds fail on downloading http://unicode.org/Public/cldr/latest/core.zip since core.zip is not available in CLDR 38.1. I don't know if it should be fixed here or in CLDR and reported this problem to [CLDR too](https://unicode-org.atlassian.net/browse/CLDR-14364). Currently the workaround is to fix CLDR version to 38:
```
cldrVersion := CLDRVersion.Version("38")
```
Maybe this file was renamed and another one should be used instead?

**Comment by cquiroz** [comment]
You need to use either `38.0` or `38.1`

**Comment by cquiroz** [comment]
And you need to upate to `sbt-locales` 2.0.1

**Comment by psttf** [comment]
Thank you! I confirm that after updating to 2.0.1 the build succeeds with the default CLDR version.
